version: "3.7"

services:
  nginx:
    build: docker/ngnix
    container_name: ngnix
    ports:
      - 8002:80
      - 8003:443
    volumes: 
    - ./docker/ngnix/servers/server1.conf:/etc/nginx/conf.d/nginx.conf
    - .:/var/www/html/
    networks: 
      - app-network

  fpm:
    build: docker/fpm
    container_name: fpm 
    volumes: 
    - .:/var/www/html/
    - ./logs/php.log:/var/log/fpm-php.www.log
    depends_on: 
    - db
    networks: 
      - app-network

  db: 
    container_name: db3
    build: docker/mysql
    ports: 
      - 3330:3306
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes: 
       - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysqld.cnf
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks: 
      - app-network


networks:
  app-network:
    driver: bridge

  
    
    
  