version: "3.7"

services:
  nginx:
    build: docker/ngnix
    container_name: ngnix
    ports:
      - 8002:80
      - 8003:443
    volumes: 
    - ./docker/ngnix/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/ngnix/servers/:/etc/nginx/servers
    - .:/projeto/

  fpm:
    build: docker/fpm
    container_name: fpm 
    volumes: 
    - .:/projeto/


networks:
  app-network:
    driver: bridge

  
    
    
  