version: "3.7"

services:
  nginx:
    build: docker/ngnix
    container_name: ngnix
    ports:
      - 8002:80
      - 8003:443
    volumes: 
    - ./docker/ngnix/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/ngnix/servers/:/etc/nginx/servers
    - .:/projeto/

  fpm:
    build: docker/fpm
    container_name: fpm 
    volumes: 
    - .:/projeto/
    depends_on: 
    - db
    networks: 
      - app-network

  db: 
    container_name: db
    build: docker/mysql
    ports: 
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks: 
      - app-network


networks:
  app-network:
    driver: bridge

  
    
    
  