FROM nginx:1.25.4

RUN mkdir -p /entrypoints
COPY ./entrypoint.sh /entrypoints/entrypoint.sh


RUN mkdir /etc/nginx/certs;

RUN openssl req -x509 -nodes -days 365 \
    -subj  "/C=CA/ST=QC/O=Company Inc/CN=example.com" \
     -newkey rsa:2048 -keyout /etc/nginx/certs/nginx-selfsigned.key \
     -out /etc/nginx/certs/nginx-selfsigned.crt;

RUN rm /etc/nginx/conf.d/default.conf

ENV DOCKERIZE_VERSION v0.7.0

RUN apt-get update \
    && apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

RUN chmod +x /entrypoints/entrypoint.sh
ENTRYPOINT ["/entrypoints/entrypoint.sh"]
   
   



